[package]
name = "tfhe"
version = "0.1.0"
authors = ["Isak Sunde Singh <isak.sunde.singh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "encryption"
harness = false
